### ISSUE TITLE
Issues with the gui and different daws.

### ISSUE THREAD

**Issue by scotttswan** [gregrecco67/AudiblePlanets#7]
having multiple instances (10-20 or so) can result in the plugin loading very slowly and the gui being white in bitwig if you run the plugin in any other mode but individual mode.

I have reported this to bitwig but there is another gui issue with reaper reported here where having multiple gui's open is causing a crash.

https://www.kvraudio.com/forum/viewtopic.php?p=8897696#p8897696

**Comment by gregrecco67** [comment]
Thanks for reporting. I'll look into it.

**Comment by scotttswan** [comment]
This is when the gui is not being displayed in bitwig,  if you click to display the gui it appears as a white blank screen.

The gui crash fix hasn't fixed this bug.

**Comment by gregrecco67** [comment]
What OS and format? And are you sure it's 1.0.22?

**Comment by gregrecco67** [comment]
I'm on Bitwig 5.1.8 and am able to run at least 10 together and am getting the UI to load without a problem now, on version 1.0.22a of the plugin.

**Comment by scotttswan** [comment]
latest bitwig (and beta) v 1.0.22 released may 7th 2024.

do you have plugin hosting mode set higher than individually or without an override?

I can get it working running individually but it obviously uses up more resources.  running by plug-in, by manufacturer or lower causes the gui issues.

**Comment by gregrecco67** [comment]
There's some perplexing behavior here I haven't been able to nail down. In Bitwig, I had the plugins loaded individually. In "By Manufacturer" mode I can load up to 9 with UI. After a crash, I can reload them one at a time and sometimes the order seems to matter. When in "By Plug-In" mode, I can load 8 or so before they crash in the same JUCE-internal drawing code I saw before and haven't been able to trace through to its cause. If you're capable, you can try building against the JUCE 8 preview branch, which I've found doesn't present the same problem. Otherwise, the only thing I can recommend at this point is to continue in individual mode in Bitwig or to refrain from opening many UI windows at once. That's the best I've got at the moment, though I'll keep investigating as I can.
